# Generated by Django 5.2 on 2025-05-11 00:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty to use product's current selling price", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
