# Generated by Django 5.2 on 2025-04-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_reset_migrations'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL to make the column nullable
            "ALTER TABLE inventory_sale ALTER COLUMN customer_id DROP NOT NULL;",
            # SQL to reverse the change (make it NOT NULL again)
            "ALTER TABLE inventory_sale ALTER COLUMN customer_id SET NOT NULL;"
        ),
    ]
