# Generated by Django 5.2 on 2025-04-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_make_customer_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            BEGIN;
            ALTER TABLE inventory_sale DROP CONSTRAINT IF EXISTS inventory_sale_customer_id_fkey;
            ALTER TABLE inventory_sale ALTER COLUMN customer_id DROP NOT NULL;
            ALTER TABLE inventory_sale ADD CONSTRAINT inventory_sale_customer_id_fkey 
                FOREIGN KEY (customer_id) REFERENCES inventory_customer(id) 
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            COMMIT;
            """,
            reverse_sql="""
            BEGIN;
            ALTER TABLE inventory_sale DROP CONSTRAINT IF EXISTS inventory_sale_customer_id_fkey;
            ALTER TABLE inventory_sale ALTER COLUMN customer_id SET NOT NULL;
            ALTER TABLE inventory_sale ADD CONSTRAINT inventory_sale_customer_id_fkey 
                FOREIGN KEY (customer_id) REFERENCES inventory_customer(id) 
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            COMMIT;
            """
        ),
    ]
